### ISSUE TITLE
"Grand Slam Exchange Format" Missing

### ISSUE THREAD

**Issue by timwattenberg** [jaykay-design/WDSF-Competition-Software-Certification#1]
The _Grand Slam Exchange Format_, linked in the wiki https://github.com/jaykay-design/WDSF-Competition-Software-Certification/wiki/#grand-slam-exchange-format, is missing.

**Comment by jaykay-design** [comment]
The Grand Slam Exchange Format is not used anymore as this was a workaround for a situation in the beginning. I will remove the section.

**Comment by timwattenberg** [comment]
I might be wrong, but to my understanding the _Grand Slam Exchange Format_ **is** still used for making scores accessible to broadcasters/the WDSF Media Team for graphics production.

**Comment by timwattenberg** [comment]
Sorry, just had a call with Stephan Rath – it seems there are **two** exchange formats:

1. The mentioned _Grand Slam Exchange Format_
2. A (undocumented) TV Exchange Format

**Comment by jaykay-design** [comment]
Oh, good to know. Could he provide that format so we can include it ehre for reference?

**Comment by timwattenberg** [comment]
As far as we know, a formal specification does not exist at this time. The implementation has been based on a "reverse engineering".

We'd be happy to formalise this for future reference, but would defer this to a less busy time, given our already packed schedules with several events coming up.

**Comment by jaykay-design** [comment]
Reverse engineered from where? :-)
No rush ...

**Comment by timwattenberg** [comment]
I wasn't involved in that process in any capacity, but I believe it was the combination of a competition software heavily used in the early developments of the absolute judging system and the "client"-implementation, developed by the WDSF Media Team 😉
